/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_gtk_TGGTK */

#ifndef _Included_org_herac_tuxguitar_gtk_TGGTK
#define _Included_org_herac_tuxguitar_gtk_TGGTK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createHeaderBar
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createHeaderBar
  (JNIEnv *, jclass);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createButtonBox
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createButtonBox
  (JNIEnv *, jclass);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createHidingScrolledWindow
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createHidingScrolledWindow
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createMenuButton
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createMenuButton
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createMenuActionItem
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createMenuActionItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createMenuCheckboxItem
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createMenuCheckboxItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createMenuRadioItem
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createMenuRadioItem
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _menuItemConnectActivated
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1menuItemConnectActivated
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createMenuSubMenuItem
 * Signature: (JLjava/lang/String;J)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createMenuSubMenuItem
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _createMenuGoBackItem
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1createMenuGoBackItem
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _menuItemSetEnabled
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1menuItemSetEnabled
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _menuItemGetEnabled
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1menuItemGetEnabled
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _headerBarPackLeft
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1headerBarPackLeft
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _headerBarPackCenter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1headerBarPackCenter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _headerBarPackRight
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1headerBarPackRight
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _windowSetHeaderBar
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1windowSetHeaderBar
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_TGGTK
 * Method:    _showAll
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_TGGTK__1showAll
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
