/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar */

#ifndef _Included_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
#define _Included_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
 * Method:    createHeaderBar
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar_createHeaderBar
  (JNIEnv *, jclass);

/*
 * Class:     org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
 * Method:    createButtonBox
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar_createButtonBox
  (JNIEnv *, jclass);

/*
 * Class:     org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
 * Method:    createHidingScrolledWindow
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar_createHidingScrolledWindow
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
 * Method:    packLeft
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar_packLeft
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
 * Method:    packCenter
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar_packCenter
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
 * Method:    packRight
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar_packRight
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar
 * Method:    setHeaderBar
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_herac_tuxguitar_gtk_headerbar_GTKHeaderBar_setHeaderBar
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
